language: python
python:
  - "2.7"
  - "3.6"
install:
  - make requirements-dev
script:
  - PYTEST_ARGS='--cov=dmapiclient --cov-report=term-missing' make test
after_success:
  - coveralls
notifications:
  email: false
